import { GlobalContextProvider } from '@/context';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });
import { Footer } from '@/components';

export const metadata: Metadata = {
  title: 'Filmoteka',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <GlobalContextProvider>
        <body className={inter.className}>
          <main>{children}</main>
          <Footer />
        </body>
      </GlobalContextProvider>
    </html>
  );
}
